[package]
name = "display_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
minifb = "0.23.0"
serialport = "4.0.1"
simple_slip = "0.1.2"

[profile.release]
opt-level = 3